export const dashboardCardData = [
  {
    title: "AI Automation",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/automationAi.png",
    bgIcon: "bg-[#ECEAF5]",
    bgButton: "bg-[#897CC0]",
  },
  {
    title: "AI Document Verification",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/docVerif.png",
    bgIcon: "bg-[#D0F9E3]",
    bgButton: "bg-[#4AC1A2]",
  },
  {
    title: "AI Location & Movement",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/location.png",
    bgIcon: "bg-[#D0E6F5]",
    bgButton: "bg-[#6C99C6]",
  },
  {
    title: "AI Capacity & Earning Power",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/earning.png",
    bgIcon: "bg-[#FEF3C7]",
    bgButton: "bg-[#E7AF52]",
  },
  {
    title: "AI Capital Strength Analysis",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/capital.png",
    bgIcon: "bg-[#D0F9E3]",
    bgButton: "bg-[#4AC1A2]",
  },
  {
    title: "AI Collateral & Guarantee",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/collateral.png",
    bgIcon: "bg-[#D0E6F5]",
    bgButton: "bg-[#6C99C6]",
  },
  {
    title: "AI Condition Analysis",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/condition.png",
    bgIcon: "bg-[#FEF3C7]",
    bgButton: "bg-[#E7AF52]",
  },
  {
    title: "AI Constraint Analysis",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/constraint.png",
    bgIcon: "bg-[#ECEAF5]",
    bgButton: "bg-[#897CC0]",
  },
  {
    title: "AI Legal & Permit Analysis",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/legalPermit.png",
    bgIcon: "bg-[#D0E6F5]",
    bgButton: "bg-[#6C99C6]",
  },
  {
    title: "AI Credit Need & Purpose",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/credit.png",
    bgIcon: "bg-[#FEF3C7]",
    bgButton: "bg-[#E7AF52]",
  },
  {
    title: "AI Digital FootPrint",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/digitalFoot.png",
    bgIcon: "bg-[#ECEAF5]",
    bgButton: "bg-[#897CC0]",
  },
  {
    title: "AI Character Analysis",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/character.png",
    bgIcon: "bg-[#D0F9E3]",
    bgButton: "bg-[#4AC1A2]",
  },
  {
    title: "AI Identity Scoring",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/identitas.png",
    bgIcon: "bg-[#FEF3C7]",
    bgButton: "bg-[#E7AF52]",
  },
  {
    title: "AI Character Scoring",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/character_scoring.png",
    bgIcon: "bg-[#ECEAF5]",
    bgButton: "bg-[#897CC0]",
  },
  {
    title: "AI Capability Scoring",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/capability.png",
    bgIcon: "bg-[#D0F9E3]",
    bgButton: "bg-[#4AC1A2]",
  },
  {
    title: "AI Credit Scoring",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/creditScoring.png",
    bgIcon: "bg-[#D0E6F5]",
    bgButton: "bg-[#6C99C6]",
  },
];
