export const fiturCards = [
  {
    title: "AI Automation",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/automationAi.png",
    bgIcon: "bg-[#ECEAF5]",
    score: 1,
  },
  {
    title: "AI Document Verification",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/docVerif.png",
    bgIcon: "bg-[#D0F9E3]",
    score: 2,
  },
  {
    title: "AI Location & Movement",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/location.png",
    bgIcon: "bg-[#D0E6F5]",
    score: 3,
  },
  {
    title: "AI Capacity & Earning Power",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/earning.png",
    bgIcon: "bg-[#FEF3C7]",
    score: 4,
  },
  {
    title: "AI Capital Strength Analysis",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/capital.png",
    bgIcon: "bg-[#D0F9E3]",
    score: 5,
  },
  {
    title: "AI Collateral & Guarantee",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/collateral.png",
    bgIcon: "bg-[#D0E6F5]",
    score: 6,
  },
  {
    title: "AI Condition Analysis",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/condition.png",
    bgIcon: "bg-[#FEF3C7]",
    score: 7,
  },
  {
    title: "AI Constraint Analysis",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/constraint.png",
    bgIcon: "bg-[#ECEAF5]",
    score: 8,
  },
  {
    title: "AI Legal & Permit Analysis",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/legalPermit.png",
    bgIcon: "bg-[#D0E6F5]",
    score: 9,
  },
  {
    title: "AI Credit Need & Purpose",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/credit.png",
    bgIcon: "bg-[#FEF3C7]",
    score: 10,
  },
  {
    title: "AI Digital FootPrint",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/digitalFoot.png",
    bgIcon: "bg-[#ECEAF5]",
    score: 11,
  },
  {
    title: "AI Character Analysis",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/character.png",
    bgIcon: "bg-[#D0F9E3]",
    score: 12,
  },
  {
    title: "AI Identity Scoring",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/identitas.png",
    bgIcon: "bg-[#FEF3C7]",
    score: 13,
  },
  {
    title: "AI Character Scoring",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/character_scoring.png",
    bgIcon: "bg-[#ECEAF5]",
    score: 14,
  },
  {
    title: "AI Capability Scoring",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/capability.png",
    bgIcon: "bg-[#D0F9E3]",
    score: 15,
  },
  {
    title: "AI Credit Scoring",
    jumlahData: "7.685",
    image: "/assets/dashboard/dashboard/creditScoring.png",
    bgIcon: "bg-[#D0E6F5]",
    score: 16,
  },
];
